import type { Metadata } from 'next';

/**
 * Shared Open Graph + Twitter card builder (M-SEO3 Part 3).
 *
 * Next.js merges metadata shallowly per top-level key, so a page that sets its
 * own `openGraph` REPLACES the root-layout default entirely (losing siteName,
 * type, etc). This helper guarantees every page emits a COMPLETE OG set —
 * og:title, og:description, og:image, og:url, og:type, og:site_name,
 * og:image:alt — plus a summary_large_image Twitter card, so each page that
 * spreads `socialMeta(...)` into its metadata stays complete on its own.
 *
 * og:image falls back to the Perfect Imprints logo when no page-specific image
 * is available; og:image:alt falls back to the title.
 */

const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || 'https://www.perfectimprints.com').replace(
  /\/$/,
  '',
);
const SITE_NAME = 'Perfect Imprints';

/** Perfect Imprints' X (Twitter) handle — used for twitter:site + twitter:creator. */
export const TWITTER_HANDLE = '@perfectimprints';

/**
 * Branded social-card fallback for og:image/twitter:image when a page has no
 * better image (e.g. CTA-only categories). MUST be a raster — X/Twitter does
 * NOT render SVG card images — so this is the 1200×630 PNG generated by
 * `scripts/seo/generate-og-default.mjs`, NOT `logo.svg`.
 */
export const LOGO_OG_IMAGE = `${SITE_URL}/og-default.png`;

/**
 * Geiger product images are stored at the 275px grid-thumbnail size
 * (`?format=webp&thumbnail=275&w=275&h=275`). That's too small/square for X's
 * `summary_large_image` card to render a LARGE image. For the SOCIAL meta only
 * (og:image + twitter:image) we bump those size params to ~1200px so X/Facebook
 * render a proper large card. The on-page grid keeps requesting 275px — this
 * only rewrites the URL handed to the social tags, never the rendered <img>.
 * Non-Geiger URLs (Sanity images, the logo) pass through unchanged.
 */
const SOCIAL_IMAGE_PX = 1200;
export function largeSocialImage(url: string | null | undefined): string | null {
  if (!url) return null;
  if (!/imgsirv\.geiger\.com/i.test(url)) return url;
  return url.replace(/\b(thumbnail|w|h)=\d+/gi, `$1=${SOCIAL_IMAGE_PX}`);
}

export interface SocialMetaInput {
  /** og:title (the descriptive page title, brand suffix optional). */
  title: string;
  description?: string;
  /** Page path ("/cat/x") or an absolute URL — becomes og:url (the canonical). */
  url: string;
  /** og:image. Null/undefined falls back to the PI logo. */
  image?: string | null;
  /** og:image:alt. Falls back to the title. */
  imageAlt?: string;
  /** og:type. "website" for listing/home, "article" for blog posts. */
  type?: 'website' | 'article';
  /** Article only — ISO publish date. */
  publishedTime?: string;
  /** Article only — ISO modified date. */
  modifiedTime?: string;
}

export function socialMeta(input: SocialMetaInput): Pick<Metadata, 'openGraph' | 'twitter'> {
  const url = /^https?:\/\//i.test(input.url) ? input.url : `${SITE_URL}${input.url}`;
  const image = input.image || LOGO_OG_IMAGE;
  const imageAlt = input.imageAlt || input.title;
  const description = input.description;
  const isArticle = input.type === 'article';

  return {
    openGraph: {
      type: input.type ?? 'website',
      siteName: SITE_NAME,
      title: input.title,
      ...(description ? { description } : {}),
      url,
      images: [{ url: image, alt: imageAlt }],
      ...(isArticle && input.publishedTime ? { publishedTime: input.publishedTime } : {}),
      ...(isArticle && input.modifiedTime ? { modifiedTime: input.modifiedTime } : {}),
    },
    twitter: {
      card: 'summary_large_image',
      site: TWITTER_HANDLE,
      creator: TWITTER_HANDLE,
      title: input.title,
      ...(description ? { description } : {}),
      images: [image],
    },
  };
}
