// @vitest-environment jsdom
/**
 * AUTO-202: the "Generate header image" button driven for real (React 19
 * `act`, the Sanity document operation and the nonce fetch mocked).
 *
 *   - With no header image it runs at once and patches the picture.
 *   - With an image it asks first; cancelling changes nothing; confirming
 *     replaces the picture.
 *   - When the AI made nothing and the chain fell back to a library picture
 *     or a product photo, an image already on the post is KEPT.
 *   - An image uploaded during the wait is kept.
 *   - The cap's refusal is shown in its own words.
 *   - It shares the running lock with the writing buttons.
 */
import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { renderToStaticMarkup } from 'react-dom/server';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const mocks = vi.hoisted(() => ({
  execute: vi.fn(),
  onComplete: vi.fn(),
  authFetch: vi.fn(),
}));

vi.mock('sanity', () => ({
  useDocumentOperation: () => ({ patch: { execute: mocks.execute } }),
}));
vi.mock('../components/useGenerateAuthFetch', () => ({
  useGenerateAuthFetch: () => mocks.authFetch,
}));

// eslint-disable-next-line import/first
import { generateBlogImageWithAi } from './generate-blog-image-with-ai';
// eslint-disable-next-line import/first
import { setBlogActionRunning } from './blog-running';

(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

type Dialog = { type?: string; header?: string; onConfirm?: () => void; onCancel?: () => void; onClose?: () => void; content?: unknown } | false | undefined;
type Description = { label?: string; onHandle?: () => void; disabled?: boolean; dialog?: Dialog } | null;
let action: Description = null;

type Props = Parameters<typeof generateBlogImageWithAi>[0];
function Harness(props: Props) {
  action = generateBlogImageWithAi(props) as Description;
  return null;
}

const generatedImage = { _type: 'image', asset: { _type: 'reference', _ref: 'image-generated-1376x768-jpg' }, alt: 'alt' };
const aiResponse = { ok: true, source: 'ai', outcome: { kind: 'asset', source: 'ai', image: generatedImage, notes: [], usage: { capUsed: 2, cap: 20 } }, summary: 'Header image: generated by the AI.' };
const productFallback = {
  ok: true,
  source: 'ai',
  outcome: { kind: 'url', source: 'product', url: 'https://imgsirv.geiger.com/master/101003/web/101003_1.jpg?w=275', alt: 'Tote', notes: ['the image model failed: 503'] },
  summary: 'Header image: the first product photo.',
};
const UPLOADED = { headerImage: { _type: 'image', asset: { _type: 'reference', _ref: 'image-uploaded-2000x1125-jpg' } } };

let root: Root;
let container: HTMLDivElement;

function propsFor(draft: Record<string, unknown>): Props {
  return {
    id: 'post-1',
    type: 'blogPost',
    draft: { _id: 'drafts.post-1', _type: 'blogPost', ...draft },
    published: null,
    onComplete: mocks.onComplete,
  } as unknown as Props;
}
async function render(props: Props) {
  await act(async () => {
    root.render(<Harness {...props} />);
  });
}
function allSets(): Record<string, unknown>[] {
  return mocks.execute.mock.calls.flatMap((call) => (call[0] as { set?: Record<string, unknown> }[]).filter((p) => p.set).map((p) => p.set as Record<string, unknown>));
}
function allUnsets(): string[] {
  return mocks.execute.mock.calls.flatMap((call) => (call[0] as { unset?: string[] }[]).filter((p) => p.unset).flatMap((p) => p.unset as string[]));
}

beforeEach(() => {
  mocks.execute.mockReset();
  mocks.onComplete.mockReset();
  mocks.authFetch.mockReset();
  mocks.authFetch.mockResolvedValue({ ok: true, json: async () => aiResponse });
  setBlogActionRunning('post-1', false);
  container = document.createElement('div');
  document.body.appendChild(container);
  root = createRoot(container);
});
afterEach(async () => {
  await act(async () => root.unmount());
  container.remove();
});

const base = { title: 'Custom Tote Bags', slug: { current: 'custom-tote-bags' }, aiTopicKeywords: ['custom tote bags'], relatedCategorySlugs: ['tote-bags'] };

describe('Generate header image', () => {
  it('with no image: runs at once, sends the title, keywords, strip SKUs and roots with source "ai", and patches the picture', async () => {
    await render(propsFor({ ...base, body: [{ _type: 'blogProducts', _key: 's', products: [{ _type: 'blogProduct', sku: '501003' }] }] }));
    expect(action!.label).toBe('Generate header image');
    await act(async () => {
      action!.onHandle!();
    });
    expect(mocks.authFetch).toHaveBeenCalledTimes(1);
    const [url, init] = mocks.authFetch.mock.calls[0] as [string, RequestInit];
    expect(url).toBe('/api/sanity/generate-blog-image');
    expect(JSON.parse(init.body as string)).toEqual({ title: 'Custom Tote Bags', keywords: ['custom tote bags'], skus: ['501003'], rootSlugs: ['tote-bags'], slug: 'custom-tote-bags', source: 'ai', postSource: undefined });
    expect(allSets()).toEqual([{ headerImage: generatedImage }]);
    expect(allUnsets()).toEqual(['externalHeaderImage']);
    const dialog = action!.dialog as Exclude<Dialog, false | undefined>;
    expect(dialog.header).toBe('Header image updated');
  });

  it('with an image: asks first; cancelling sends nothing; confirming replaces it', async () => {
    await render(propsFor({ ...base, ...UPLOADED }));
    expect(action!.label).toBe('Generate another header image');
    await act(async () => {
      action!.onHandle!();
    });
    let dialog = action!.dialog as Exclude<Dialog, false | undefined>;
    expect(dialog.type).toBe('confirm');
    expect(mocks.authFetch).not.toHaveBeenCalled();
    await act(async () => {
      dialog.onCancel!();
    });
    expect(mocks.authFetch).not.toHaveBeenCalled();
    expect(mocks.execute).not.toHaveBeenCalled();

    await act(async () => {
      action!.onHandle!();
    });
    dialog = action!.dialog as Exclude<Dialog, false | undefined>;
    await act(async () => {
      dialog.onConfirm!();
    });
    expect(mocks.authFetch).toHaveBeenCalledTimes(1);
    expect(allSets()).toEqual([{ headerImage: generatedImage }]);
  });

  it('a fallback picture never replaces an image already on the post; it may fill an empty one', async () => {
    mocks.authFetch.mockResolvedValue({ ok: true, json: async () => productFallback });
    await render(propsFor({ ...base, ...UPLOADED }));
    await act(async () => {
      action!.onHandle!();
    });
    await act(async () => {
      (action!.dialog as { onConfirm: () => void }).onConfirm();
    });
    expect(mocks.execute).not.toHaveBeenCalled();
    expect((action!.dialog as { header?: string }).header).toBe('Your image was kept');

    mocks.execute.mockReset();
    await act(async () => root.unmount());
    root = createRoot(container);
    await render(propsFor(base));
    await act(async () => {
      action!.onHandle!();
    });
    expect(allSets()).toEqual([{ externalHeaderImage: { url: productFallback.outcome.url, alt: 'Tote' } }]);
    expect(allUnsets()).toEqual(['headerImage']);
  });

  it('an image uploaded during the wait is kept', async () => {
    let resolve!: (v: unknown) => void;
    mocks.authFetch.mockReturnValue(new Promise((r) => (resolve = r)));
    await render(propsFor(base));
    await act(async () => {
      action!.onHandle!();
    });
    await render(propsFor({ ...base, ...UPLOADED }));
    await act(async () => {
      resolve({ ok: true, json: async () => aiResponse });
    });
    expect(mocks.execute).not.toHaveBeenCalled();
    expect((action!.dialog as { header?: string }).header).toBe('Your image was kept');
  });

  it("the cap's refusal is shown in its own words and nothing is changed", async () => {
    mocks.authFetch.mockResolvedValue({
      ok: true,
      json: async () => ({ ok: true, source: 'ai', outcome: { kind: 'none', notes: ['The daily limit of 20 generated header images has been reached, so no image was made. The limit resets at midnight UTC (evening in Florida).'] }, summary: 'Header image: none.' }),
    });
    await render(propsFor(base));
    await act(async () => {
      action!.onHandle!();
    });
    expect(mocks.execute).not.toHaveBeenCalled();
    const dialog = action!.dialog as { header?: string; content?: React.ReactElement };
    expect(dialog.header).toBe('No header image was made');
    expect(renderToStaticMarkup(dialog.content as React.ReactElement)).toContain('The daily limit of 20 generated header images has been reached');
  });

  it('is disabled while a writing button runs on the same document, and without a title', async () => {
    await render(propsFor(base));
    expect(action!.disabled).toBe(false);
    setBlogActionRunning('post-1', true);
    await render(propsFor(base));
    expect(action!.disabled).toBe(true);
    setBlogActionRunning('post-1', false);
    await render(propsFor({ ...base, title: '' }));
    expect(action!.disabled).toBe(true);
  });
});
