// @vitest-environment jsdom
/**
 * AUTO-116: the two blog AI actions driven for real (React 19 `act`, the
 * Sanity document operation and the nonce fetch mocked), and the patch each
 * one executes inspected.
 *
 *   - "Generate Blog with AI" cannot overwrite a field that has anything in
 *     it, for every field it touches, and sends nothing to the AI when
 *     nothing is empty.
 *   - "Regenerate Blog with AI" sends nothing and patches nothing until the
 *     confirmation is accepted.
 *   - A field typed into during the wait is kept.
 *   - While one button runs, both are disabled.
 *
 * AUTO-202, the header image:
 *   - FILL makes a picture (a second request, to the image route) only when
 *     the post has NO header image; an uploaded image is NEVER replaced, and
 *     the image route is not even called.
 *   - When every text field is written and only the image is missing, FILL
 *     makes the image and nothing else.
 *   - REGENERATE's confirmation names "Header image"; after confirming it
 *     asks for a new picture and replaces the old one.
 *   - An image uploaded during the wait is kept.
 *   - A failed picture never fails the post.
 */
import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { renderToStaticMarkup } from 'react-dom/server';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const mocks = vi.hoisted(() => ({
  execute: vi.fn(),
  onComplete: vi.fn(),
  authFetch: vi.fn(),
}));

vi.mock('sanity', () => ({
  useDocumentOperation: () => ({ patch: { execute: mocks.execute } }),
}));
vi.mock('../components/useGenerateAuthFetch', () => ({
  useGenerateAuthFetch: () => mocks.authFetch,
}));

// eslint-disable-next-line import/first
import { generateBlogWithAi, regenerateBlogWithAi } from './generate-blog-with-ai';

(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

type Dialog = { type?: string; message?: unknown; onConfirm?: () => void; onCancel?: () => void } | false | undefined;
type Description = { onHandle?: () => void; disabled?: boolean; dialog?: Dialog } | null;
let fill: Description = null;
let regen: Description = null;

type Props = Parameters<typeof generateBlogWithAi>[0];
function Harness(props: Props) {
  fill = generateBlogWithAi(props) as Description;
  regen = regenerateBlogWithAi(props) as Description;
  return null;
}

const block = (text: string) => ({
  _type: 'block',
  _key: 'b',
  style: 'normal',
  markDefs: [],
  children: [{ _type: 'span', _key: 's', text, marks: [] }],
});

const strip = { _type: 'blogProducts', _key: 'bp', products: [{ _type: 'blogProduct', _key: 'p', sku: '501003' }] };

const routeResponse = {
  title: 'AI Title For Water Bottles',
  metaTitle: 'AI meta title',
  metaDescription: 'AI meta description',
  excerpt: 'AI excerpt',
  body: [block('AI body'), strip],
  suggestedLinks: [{ label: 'Water bottles', href: '/cat/water-bottles', reason: 'r' }],
};

const generatedImage = { _type: 'image', asset: { _type: 'reference', _ref: 'image-generated-1376x768-jpg' }, alt: 'Custom water bottles (illustrative image)' };
const imageResponse = {
  ok: true,
  source: 'ai',
  outcome: { kind: 'asset', source: 'ai', image: generatedImage, notes: [], usage: { capUsed: 1, cap: 20, attempts: 1 } },
  summary: "Header image: generated by the AI from the post's product photos.",
};

const MINE = {
  metaTitle: 'My meta title',
  metaDescription: 'My meta description',
  excerpt: 'My excerpt',
  body: [block('My own paragraph'), { _type: 'image', _key: 'i', asset: { _ref: 'image-x' } }],
} as const;
type ContentField = keyof typeof MINE;
const FIELDS = Object.keys(MINE) as ContentField[];

/** A header image Patrick uploaded himself. */
const UPLOADED = { headerImage: { _type: 'image', asset: { _type: 'reference', _ref: 'image-uploaded-by-patrick-2000x1125-jpg' } } };

let root: Root;
let container: HTMLDivElement;

function propsFor(draft: Record<string, unknown>, published: Record<string, unknown> | null = null): Props {
  return {
    id: 'post-1',
    type: 'blogPost',
    draft: { _id: 'drafts.post-1', _type: 'blogPost', ...draft },
    published,
    onComplete: mocks.onComplete,
  } as unknown as Props;
}

async function render(props: Props) {
  await act(async () => {
    root.render(<Harness {...props} />);
  });
}

/** Every `set` executed so far, in order. */
function allSets(): Record<string, unknown>[] {
  return mocks.execute.mock.calls.flatMap((call) => (call[0] as { set?: Record<string, unknown> }[]).filter((p) => p.set).map((p) => p.set as Record<string, unknown>));
}
function allUnsets(): string[] {
  return mocks.execute.mock.calls.flatMap((call) => (call[0] as { unset?: string[] }[]).filter((p) => p.unset).flatMap((p) => p.unset as string[]));
}
/** The body patch (the first `set`), for the content assertions. */
function firstSet(): Record<string, unknown> {
  const sets = allSets();
  expect(sets.length).toBeGreaterThan(0);
  return sets[0];
}
function urlsCalled(): string[] {
  return mocks.authFetch.mock.calls.map((c) => c[0] as string);
}
function bodyOfCall(index: number): Record<string, unknown> {
  return JSON.parse((mocks.authFetch.mock.calls[index][1] as RequestInit).body as string);
}

/** The default fetch: the blog route answers the post, the image route a generated picture. */
function routeByUrl(url: string) {
  if (url === '/api/sanity/generate-blog-image') return { ok: true, json: async () => imageResponse };
  return { ok: true, json: async () => routeResponse };
}

beforeEach(() => {
  mocks.execute.mockReset();
  mocks.onComplete.mockReset();
  mocks.authFetch.mockReset();
  mocks.authFetch.mockImplementation(async (url: string) => routeByUrl(url));
  container = document.createElement('div');
  document.body.appendChild(container);
  root = createRoot(container);
});

afterEach(async () => {
  await act(async () => root.unmount());
  container.remove();
});

describe('Generate Blog with AI (fills empty fields only)', () => {
  it.each(FIELDS)('cannot overwrite a non-empty %s, and fills the empty ones; an uploaded header image is never touched', async (field) => {
    await render(propsFor({ title: 'Water bottles', slug: { current: 'water-bottles' }, [field]: MINE[field], ...UPLOADED }));
    await act(async () => {
      fill!.onHandle!();
    });
    // One request: the post. The image route is not called when an image exists.
    expect(urlsCalled()).toEqual(['/api/sanity/generate-blog']);
    const set = firstSet();
    expect(field in set).toBe(false);
    expect('title' in set).toBe(false);
    expect('slug' in set).toBe(false);
    expect('publishDate' in set).toBe(false);
    expect('headerImage' in set).toBe(false);
    expect(allUnsets()).toEqual([]);
    for (const other of FIELDS.filter((f) => f !== field)) expect(set[other]).toEqual(routeResponse[other]);
    // Suggested links describe the generated body, so they go only with it.
    expect('aiSuggestedLinks' in set).toBe(field !== 'body');
  });

  it('sends nothing to the AI and changes nothing when every AI field is filled, the image included', async () => {
    await render(propsFor({ title: 'Water bottles', slug: { current: 'water-bottles' }, ...MINE, ...UPLOADED }));
    await act(async () => {
      fill!.onHandle!();
    });
    expect(mocks.authFetch).not.toHaveBeenCalled();
    expect(mocks.execute).not.toHaveBeenCalled();
  });

  it('keeps a field typed into while the AI was writing', async () => {
    let resolve!: (v: unknown) => void;
    mocks.authFetch.mockImplementation(async (url: string) => {
      if (url === '/api/sanity/generate-blog') return new Promise((r) => (resolve = r));
      return routeByUrl(url);
    });
    await render(propsFor({ title: 'Water bottles', slug: { current: 'water-bottles' }, ...UPLOADED }));
    await act(async () => {
      fill!.onHandle!();
    });
    // Patrick types an excerpt during the wait.
    await render(propsFor({ title: 'Water bottles', slug: { current: 'water-bottles' }, excerpt: 'Typed while waiting', ...UPLOADED }));
    await act(async () => {
      resolve({ ok: true, json: async () => routeResponse });
    });
    const set = firstSet();
    expect('excerpt' in set).toBe(false);
    expect(set.body).toEqual(routeResponse.body);
  });

  it('disables BOTH buttons while it runs', async () => {
    let resolve!: (v: unknown) => void;
    mocks.authFetch.mockImplementation(async (url: string) => {
      if (url === '/api/sanity/generate-blog') return new Promise((r) => (resolve = r));
      return routeByUrl(url);
    });
    await render(propsFor({ title: 'Water bottles', ...UPLOADED }));
    expect(fill!.disabled).toBe(false);
    expect(regen!.disabled).toBe(false);
    await act(async () => {
      fill!.onHandle!();
    });
    expect(fill!.disabled).toBe(true);
    expect(regen!.disabled).toBe(true);
    await act(async () => {
      resolve({ ok: true, json: async () => routeResponse });
    });
    expect(fill!.disabled).toBe(false);
    expect(regen!.disabled).toBe(false);
  });

  it('a failed generation changes nothing, and asks for no picture', async () => {
    mocks.authFetch.mockResolvedValue({ ok: false, status: 502, json: async () => ({ error: 'Too thin, try again.' }) });
    await render(propsFor({ title: 'Water bottles' }));
    await act(async () => {
      fill!.onHandle!();
    });
    expect(mocks.execute).not.toHaveBeenCalled();
    expect(urlsCalled()).toEqual(['/api/sanity/generate-blog']);
  });
});

describe('the header image (AUTO-202)', () => {
  it('FILL on a post with no image asks the image route after the body is patched, from the body it just patched, and sets the picture', async () => {
    await render(propsFor({ title: 'Water bottles', slug: { current: 'water-bottles' }, aiTopicKeywords: ['custom water bottles'], headerImageSource: 'library' }));
    await act(async () => {
      fill!.onHandle!();
    });
    expect(urlsCalled()).toEqual(['/api/sanity/generate-blog', '/api/sanity/generate-blog-image']);
    expect(bodyOfCall(1)).toEqual({
      title: 'Water bottles',
      keywords: ['custom water bottles'],
      skus: ['501003'],
      rootSlugs: [],
      slug: 'water-bottles',
      source: 'default',
      postSource: 'library',
    });
    const sets = allSets();
    expect(sets[0].body).toEqual(routeResponse.body);
    expect(sets[1]).toEqual({ headerImage: generatedImage });
    expect(allUnsets()).toEqual(['externalHeaderImage']);
  });

  it('FILL with every text field written and no image makes the image and nothing else', async () => {
    await render(propsFor({ title: 'Water bottles', slug: { current: 'water-bottles' }, ...MINE }));
    await act(async () => {
      fill!.onHandle!();
    });
    expect(urlsCalled()).toEqual(['/api/sanity/generate-blog-image']);
    expect(bodyOfCall(0).source).toBe('default');
    expect(allSets()).toEqual([{ headerImage: generatedImage }]);
  });

  it('an uploaded image is never replaced by FILL, whatever the source setting says', async () => {
    await render(propsFor({ title: 'Water bottles', slug: { current: 'water-bottles' }, ...MINE, ...UPLOADED, headerImageSource: 'ai' }));
    await act(async () => {
      fill!.onHandle!();
    });
    expect(urlsCalled()).toEqual([]);
    expect(mocks.execute).not.toHaveBeenCalled();
  });

  it('an image uploaded during the wait is kept: the generated picture is not put on the post', async () => {
    let resolveImage!: (v: unknown) => void;
    mocks.authFetch.mockImplementation(async (url: string) => {
      if (url === '/api/sanity/generate-blog-image') return new Promise((r) => (resolveImage = r));
      return routeByUrl(url);
    });
    await render(propsFor({ title: 'Water bottles', slug: { current: 'water-bottles' }, ...MINE }));
    await act(async () => {
      fill!.onHandle!();
    });
    // Patrick uploads his own while the picture is being made.
    await render(propsFor({ title: 'Water bottles', slug: { current: 'water-bottles' }, ...MINE, ...UPLOADED }));
    await act(async () => {
      resolveImage({ ok: true, json: async () => imageResponse });
    });
    expect(allSets()).toEqual([]);
  });

  it('the product-photo fallback is written as the hot link and clears the asset', async () => {
    mocks.authFetch.mockImplementation(async (url: string) => {
      if (url === '/api/sanity/generate-blog-image') {
        return {
          ok: true,
          json: async () => ({ ok: true, outcome: { kind: 'url', source: 'product', url: 'https://imgsirv.geiger.com/master/101003/web/101003_1.jpg?w=275', alt: 'Bottle', notes: ['the image model failed: 503'] }, summary: 'Header image: the first product photo.' }),
        };
      }
      return routeByUrl(url);
    });
    await render(propsFor({ title: 'Water bottles', slug: { current: 'water-bottles' }, ...MINE }));
    await act(async () => {
      fill!.onHandle!();
    });
    expect(allSets()).toEqual([{ externalHeaderImage: { url: 'https://imgsirv.geiger.com/master/101003/web/101003_1.jpg?w=275', alt: 'Bottle' } }]);
    expect(allUnsets()).toEqual(['headerImage']);
  });

  it('a failed picture never fails the post: the body patch stands and no image is set', async () => {
    mocks.authFetch.mockImplementation(async (url: string) => {
      if (url === '/api/sanity/generate-blog-image') return { ok: false, status: 429, json: async () => ({ error: 'The daily limit of 20 generated header images has been reached.' }) };
      return routeByUrl(url);
    });
    await render(propsFor({ title: 'Water bottles', slug: { current: 'water-bottles' } }));
    await act(async () => {
      fill!.onHandle!();
    });
    const sets = allSets();
    expect(sets).toHaveLength(1);
    expect(sets[0].body).toEqual(routeResponse.body);
    expect(fill!.dialog && (fill!.dialog as { type?: string }).type).toBe('dialog');
  });
});

describe('Regenerate Blog with AI (replaces, after confirmation)', () => {
  const full = { title: 'Water bottles', slug: { current: 'water-bottles' }, ...MINE, ...UPLOADED };

  it('sends nothing and patches nothing until confirmed, and the confirmation names the header image', async () => {
    await render(propsFor(full));
    await act(async () => {
      regen!.onHandle!();
    });
    expect(mocks.authFetch).not.toHaveBeenCalled();
    expect(mocks.execute).not.toHaveBeenCalled();
    const dialog = regen!.dialog as Exclude<Dialog, false | undefined>;
    expect(dialog.type).toBe('confirm');
    const html = renderToStaticMarkup(dialog.message as React.ReactElement);
    expect(html).toContain('This replaces:');
    expect(html).toContain('Header image');
  });

  it('cancelling leaves the post exactly as it was', async () => {
    await render(propsFor(full));
    await act(async () => {
      regen!.onHandle!();
    });
    await act(async () => {
      (regen!.dialog as { onCancel: () => void }).onCancel();
    });
    expect(mocks.authFetch).not.toHaveBeenCalled();
    expect(mocks.execute).not.toHaveBeenCalled();
    expect(regen!.dialog).toBe(false);
  });

  it('after confirming, replaces the fields, moves title and slug together, and replaces the header image', async () => {
    await render(propsFor(full));
    await act(async () => {
      regen!.onHandle!();
    });
    await act(async () => {
      (regen!.dialog as { onConfirm: () => void }).onConfirm();
    });
    expect(urlsCalled()).toEqual(['/api/sanity/generate-blog', '/api/sanity/generate-blog-image']);
    const set = firstSet();
    for (const f of FIELDS) expect(set[f]).toEqual(routeResponse[f]);
    expect(set.title).toBe(routeResponse.title);
    expect(set.slug).toEqual({ _type: 'slug', current: 'ai-title-for-water-bottles' });
    expect('publishDate' in set).toBe(false);
    expect(allSets()[1]).toEqual({ headerImage: generatedImage });
  });

  it('on a published post, never touches the title or the slug', async () => {
    await render(propsFor(full, { _id: 'post-1', _type: 'blogPost', ...full }));
    await act(async () => {
      regen!.onHandle!();
    });
    await act(async () => {
      (regen!.dialog as { onConfirm: () => void }).onConfirm();
    });
    const set = firstSet();
    expect('title' in set).toBe(false);
    expect('slug' in set).toBe(false);
    expect(set.body).toEqual(routeResponse.body);
  });
});
